### ISSUE TITLE
Feature Request: CKAN release

### ISSUE THREAD

**Issue by mwerle** [Kerbas-ad-astra/HGR-Community-Fixes#8]
Would be nice to deprecate the original HGR in CKAN and replace it with HGR-CF. Any plans to do so?

**Comment by Kerbas-ad-astra** [comment]
It's not a priority.  I don't use CKAN, so there's no benefit to me, and there's other development that needs addressing first (heat shields and localization).

**Comment by mwerle** [comment]
Umm, so why close the feature request instead of just leaving it open at low priority? I'd even see about doing it if I can find some spare time. Anyway.
